# Generated by Django 5.0.1 on 2024-11-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_enrollment_status_alter_enrollment_grade_percentage_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together={("student", "module")},
        ),
        migrations.RemoveField(
            model_name="module",
            name="currently_enrolled",
        ),
        migrations.RemoveField(
            model_name="module",
            name="module_code",
        ),
        migrations.RemoveField(
            model_name="module",
            name="students",
        ),
        migrations.RemoveField(
            model_name="module",
            name="title",
        ),
        migrations.AddField(
            model_name="enrollment",
            name="date_enrolled",
            field=models.DateField(auto_now_add=True, default="2023-01-01"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="enrollment",
            name="grade",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="module",
            name="name",
            field=models.CharField(default="default name", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="student",
            name="date_of_birth",
            field=models.DateField(default="2023-01-01"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="student",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.RemoveField(
            model_name="enrollment",
            name="grade_percentage",
        ),
        migrations.RemoveField(
            model_name="enrollment",
            name="status",
        ),
    ]
