# Generated by Django 5.0.1 on 2024-11-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_student_student_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="student_id",
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
